# If you see me, please update my `rev` field using the provided links
# Click the repo and update to latest tags.
# If things break on update, raise an issue
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort imports deepcave
        files: deepcave

      - id: isort
        name: isort imports tests
        files: tests

  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
        name: black formatter deepcave
        files: deepcave

      - id: black
        name: black formatter tests
        files: tests

      - id: black
        name: black formatter examples
        files: examples

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        files: deepcave
        additional_dependencies: ["tomli"] # Needed to parse pyproject.toml

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        name: mypy deepcave
        files: deepcave
        args: [--install-types, --non-interactive]
        additional_dependencies: [
            'wheel>=0.41.2',
            'setuptools==68.2.2',
            'absl-py>=1.0.0',
            'jsonlines>=3.0.0',
            'pandas>=1.3.4',
            'numpy>=2.0.1',
            'matplotlib==3.9.0',
            'seaborn>=0.13.0',
            'pyyaml>=6.0.1',
            'kaleido>=0.2.1',
            'gplearn>=0.4.2',
            'sympy>=1.12',
            'requests>=2.31.0',
            'ConfigSpace==1.2.0',
            'pyrfr>=0.9.0',
            'hpbandster==0.7.4',
            'dash==2.0.0',
            'dash-extensions==0.0.71',
            'dash-bootstrap-components==1.0.3',
            'redis>=4.1.4',
            'rq>=1.10.1',
            'werkzeug==2.0.3',
            'pyarrow==16.1.0',
            'fastparquet==2024.5.0',
            'pyPDPPartitioner>=0.1.9'
        ] # Needed for mypy, so that it knows the types to check

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: flake8 deepcave
        files: deepcave

      - id: flake8
        name: flake8 tests
        files: tests
